name       : perl-number-compare
version    : 0.03
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RC/RCLAMP/Number-Compare-0.03.tar.gz : 83293737e803b43112830443fb5208ec5208a2e6ea512ed54ef8e4dd2b880827
license    : GPL-2.0
component  : programming.perl
summary    : compiles a simple comparison to an anonymous subroutine, which you can
    call with a value to be tested again
description: |
    compiles a simple comparison to an anonymous subroutine, which you can call with a value to be tested again
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
